-- SCOTT.BBS definition

CREATE TABLE "SCOTT"."BBS2" 
   (	"no" NUMBER, 
	"TITLE" VARCHAR2(100) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(100) NOT NULL ENABLE, 
	"WRITER" VARCHAR2(100), 
	 CONSTRAINT "BBS_PK2" PRIMARY KEY ("no")
)

CREATE SEQUENCE seq111 INCREMENT BY 1 START WITH 1

INSERT INTO bbs2 values(seq111.nextval, 't2', 'c2', 'park')

SELECT * FROM bbs2

-- SCOTT.BBS definition

CREATE TABLE "SCOTT"."BBS11" 
   (	"no" NUMBER, 
	"TITLE" VARCHAR2(100) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(100) NOT NULL ENABLE, 
	"WRITER" VARCHAR2(100), 
	 CONSTRAINT "BBS_PK" PRIMARY KEY ("no")
)	 
	 
	 
	 
	 
	 
	 
	 
	 
