CREATE TABLE test11(
	id varchar2(100) PRIMARY KEY,
	name varchar2(100) UNIQUE
);
INSERT INTO test1 values('123', '123');
INSERT INTO test1 values('111', '111');

CREATE TABLE test22(
	id varchar2(100),
	name varchar2(100),
	CONSTRAINT "ZTEST_FK11" FOREIGN KEY(id) REFERENCES "SCOTT"."TEST1" (id),
	CONSTRAINT "ZTEST_FK22" FOREIGN KEY(name) REFERENCES "SCOTT"."TEST1" (name)
);
INSERT INTO test2 values('111', '111');

DROP TABLE test22;

SELECT * FROM user_CONSTRAINTS;

-- -------------------date test

INSERT INTO SCOTT.EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(100, '1', '1', 0, '2022-01-01', 0, 0, 10);

INSERT INTO SCOTT.EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(300, '1', '1', 0, to_date('2022/01/01', 'YYYY/MM/DD'), 0, 0, 10)

INSERT INTO SCOTT.EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(400, '1', '1', 0, to_date(sysdate), 0, 0, 10)

INSERT INTO SCOTT.EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(500, '1', '1', 0, sysdate, 0, 0, 10)


SELECT * FROM emp ORDER BY hiredate desc
